# try and exception handling

a = input("enter \n")
b = input("enter \n")
try :    #using of try 

    print("Addition of two no.", int(a)+int(b))
except Exception as a: # using of except and syantax of except key word
    print(a)
print("this is very important line")